CREATE TABLE IF NOT EXISTS NOTIFICATION(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT VARCHAR(100) NOT NULL,
    IS_READ  BOOLEAN,
    IS_HIDDEN BOOLEAN,
    CREATED_BY VARCHAR(255) DEFAULT 'USER',
    CREATED_DATE_TIME TIMESTAMP
);

CREATE TABLE IF NOT EXISTS USER_NOTIFICATION(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    MESSAGE_ID INTEGER UNIQUE ,
    FROM_USER INTEGER  NOT NULL,
    TO_USER  INTEGER NOT NULL,
    FOREIGN KEY (MESSAGE_ID) REFERENCES NOTIFICATION(ID)
);